# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d46aef9c713245f32270bada1d5edbf77c533c4761ee5c774868557fc121fe7b31f8fa9e9cc611b35cfa9008cbf04cc2885b7d8dad0f093b5fc25177ad15544

test:
  secret_key_base: 1ec53788a38945e7b4d066205dff0a22b7aed851e727bee1f047bfa48f54b7069f3adc09dea5f47749bd3b21615034a4dc89961955a91ec5ebbfa9e68f14603d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
